name: pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - cffi=1.15.0=py310h2bbff1b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py310h21b164f_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - freetype=2.10.4=hd328e21_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9e=h2bbff1b_0
  - libffi=3.4.2=hd77b12b_4
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=he0120a3_1
  - libuv=1.40.0=he774522_0
  - lz4-c=1.9.3=h2bbff1b_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - numpy=1.22.3=py310h6d2d95c_0
  - numpy-base=1.22.3=py310h206c741_0
  - pillow=9.0.1=py310hdc2b20a_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.4=hbb2ffb3_0
  - pytorch=1.12.0=py3.10_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - requests=2.28.0=py310haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - torchaudio=0.12.0=py310_cu113
  - torchvision=0.13.0=py310_cu113
  - typing_extensions=4.1.1=pyh06a4308_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - zlib=1.2.12=h8cc25b3_2
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - absl-py==1.2.0
    - accelerate==0.12.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - altair==4.2.2
    - altgraph==0.17.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asgiref==3.5.2
    - asttokens==2.0.5
    - async-timeout==4.0.2
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blinker==1.6.2
    - cachetools==5.2.0
    - certifi==2022.9.24
    - click==8.1.3
    - cloudpickle==2.0.0
    - colorama==0.4.5
    - cos-python-sdk-v5==1.9.24
    - crcmod==1.7
    - cx-freeze==6.14.9
    - cx-logging==3.1.0
    - cycler==0.11.0
    - d2l==0.15.1
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - django==4.1.2
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - flatbuffers==23.3.3
    - fonttools==4.33.3
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.48.1
    - imageio==2.22.4
    - importlib-metadata==6.5.0
    - ipykernel==6.15.0
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.6.1
    - jupyter==1.0.0
    - jupyter-client==7.3.4
    - jupyter-console==6.4.4
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.1
    - kiwisolver==1.4.3
    - libretranslatepy==2.1.1
    - lief==0.13.0
    - lmdb==1.3.0
    - lxml==4.9.1
    - markdown==3.4.1
    - markdown-it-py==2.2.0
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mdurl==0.1.2
    - mediapipe==0.9.1.0
    - mistune==0.8.4
    - multidict==6.0.2
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.8.8
    - nose==1.3.7
    - notebook==6.4.12
    - oauthlib==3.2.1
    - onnx==1.14.0
    - opencv-contrib-python==4.7.0.72
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.6.0.66
    - openpyxl==3.0.10
    - packaging==21.3
    - pandas==1.4.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pefile==2023.2.7
    - pickleshare==0.7.5
    - pip==23.1.2
    - pipreqs==0.4.11
    - prometheus-client==0.14.1
    - promise==2.3
    - prompt-toolkit==3.0.30
    - protobuf==3.19.1
    - psutil==5.9.1
    - pure-eval==0.2.2
    - pyarrow==11.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodome==3.17
    - pydeck==0.8.1b0
    - pydeprecate==0.3.2
    - pygments==2.15.1
    - pyinstaller==5.8.0
    - pyinstaller-hooks-contrib==2023.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyrsistent==0.18.1
    - pyside6==6.5.0
    - pyside6-addons==6.5.0
    - pyside6-essentials==6.5.0
    - python-dateutil==2.8.2
    - pytorch-lightning==1.7.5
    - pytz==2022.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - pywin32==304
    - pywin32-ctypes==0.2.0
    - pywinpty==2.0.5
    - pyyaml==6.0
    - pyzmq==23.2.0
    - qt-material==2.14
    - qtconsole==5.3.1
    - qtpy==2.1.0
    - qudida==0.0.4
    - requests-oauthlib==1.3.1
    - resnest==0.0.6b20210114
    - rich==13.3.4
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.8.1
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sentry-sdk==1.9.8
    - setproctitle==1.3.2
    - setuptools==67.6.1
    - shiboken6==6.5.0
    - shortuuid==1.0.9
    - sklearn==0.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - sqlparse==0.4.3
    - stack-data==0.3.0
    - streamlit==1.21.0
    - streamlit-drawable-canvas==0.9.2
    - svgwrite==1.4.3
    - tabulate==0.9.0
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - terminado==0.15.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - tinycss2==1.1.1
    - toml==0.10.2
    - toolz==0.12.0
    - torchkeras==3.2.3
    - torchmetrics==0.9.3
    - torchsummary==1.5.1
    - tornado==6.2
    - tqdm==4.64.0
    - traitlets==5.3.0
    - translate==3.6.1
    - tree==0.2.4
    - tzdata==2022.5
    - tzlocal==4.3
    - ultralytics==8.0.83
    - uni-sdk==0.2.0
    - unisms==0.0.7
    - urllib3==1.26.12
    - validators==0.20.0
    - wandb==0.13.3
    - watchdog==3.0.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.2.2
    - widgetsnbextension==3.6.1
    - xmltodict==0.13.0
    - yacs==0.1.8
    - yarg==0.1.9
    - yarl==1.8.1
    - zipp==3.15.0
prefix: C:\Users\yujunyu\.conda\envs\pytorch
[0m[0m